export const START_FETCHING_DATA = "features/Home/START_FETCHING_DATA";
export const ERROR_FETCHING_DATA = "features/Home/ERROR_FETCHING_DATA";
export const SUCCESS_FETCHING_DATA = "features/Home/SUCCESS_FETCHING_DATA";
export const SET_DATA_SESI_UJIAN = "features/Home/SET_DATA_SESI_UJIAN";
export const SUCCESS_UJIAN_STATUS_CHECK =
  "features/Home/SUCCESS_UJIAN_STATUS_CHECK";
export const SUCCESS_GET_DATA_CHECK_UJIAN =
  "features/Home/SUCCESS_GET_DATA_CHECK_UJIAN";
export const SUCCESS_GET_DATA_QUIZ_BY_ID =
  "features/Home/SUCCESS_GET_DATA_QUIZ_BY_ID";
